# enviroment settings
environment:
  JAVA_HOME: C:\Program Files\Java\jdk9
  MAVEN_OPTS: -Xmx4g
  JAVA_OPTS: -Xmx4g
  M2: $(USERPROFILE)\.m2

# install required tools (maven, secure-file, encrypted files)
install:
  #- cinst jdk10 -params 'installdir=C:\\jdk10'
  # - SET JAVA_HOME=C:\Program Files\Java\jdk9
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: echo %M2_HOME%

build_script:
  - mvn clean install -DskipTests

 # verify artifacts
test_script:
  - mvn verify

cache:
  - C:\Users\appveyor\.m2
  - '%MAVEN_HOME%'
  - '%M2%'
  - maven\target\m2
  #- C:\jdk10
